name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.3.0
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: they always use the latest patch version.
        version: v1.31

    - name: Test
      run: make test
      env:
        INFRACOST_API_KEY: "00000000000000000000000000000000"
        INFRACOST_LOG_LEVEL: info

    - name: Test example works ok from CLI
      run: |
        make run --silent ARGS="--terraform-dir examples/terraform --usage-file=examples/terraform/infracost-usage.yml --format json" > infracost-output.json
        jq '' infracost-output.json
      env:
        INFRACOST_API_KEY: "00000000000000000000000000000000"
        INFRACOST_LOG_LEVEL: info

    - name: Test example works ok from config file
      run: |
        make run --silent ARGS="--config-file=infracost-example.yml"
        jq '' infracost-output.json
      env:
        INFRACOST_API_KEY: "00000000000000000000000000000000"
        INFRACOST_LOG_LEVEL: info
